#!/bin/bash

files=(src/toupee.js src/toupee/browser.js src/toupee/html.js src/toupee/buttons.js src/toupee/selection.js)

if [ ! -d dist ]; then
  mkdir dist
fi

if [ -f dist/toupee.js ]; then
  rm dist/toupee.js
fi

for file in ${files[@]}; do
  cat ${file} >> dist/toupee.js
  echo $'\n' >> dist/toupee.js
done